apiVersion: apps/v1
kind: Deployment
metadata:
  name: cw2-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cw2-app
  template:
    metadata:
      labels:
        app: cw2-app
    spec:
      containers:
      - name: cw2-server
        image: oliver1403/cw2-server:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cw2-service
spec:
  type: NodePort
  selector:
    app: cw2-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31018
